project:
  type: website

website:
  site-url: https://netique.github.io/tmws/
  title: "Topic modeling workshop"
  comments:
    giscus:
      repo: netique/tmws
  repo-url: https://github.com/netique/tmws/
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card:
    site: "@netikja"
  page-footer:
    center:
      - text: "© 2023 Jan Netík"
      - text: "CC BY-SA 4.0"
        href: "https://creativecommons.org/licenses/by-sa/4.0/"
        target: blank
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Úvod
      - href: setup.qmd
        text: Příprava
    tools:
      - icon: github
        href: https://github.com/netique/tmws/

format:
  html:
    theme:
      light: default
      dark: darkly
    toc: true
    html-math-method: katex
    link-external-icon: false
    link-external-newwindow: true
    code-overflow: wrap
    code-tools: true

editor: visual
lang: cs-CZ

