project:
  type: website

website:
  site-url: https://netique.github.io/tmws/
  title: "Topic modeling workshop"
  search: false
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Úvod
      - href: setup.qmd
        text: Příprava
    tools:
      - icon: github
        href: https://github.com/netique/tmws/

format:
  html:
    theme:
      light: default
      dark: darkly
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    code-overflow: wrap
    code-tools: true

editor: visual
lang: cs-CZ

