---
title: "P콏칤prava"
---

N칤쬰 je seznam v캩c칤, kter칠 v r치mci workshopu pravd캩podobn캩 vyu쬴jeme. Mezi nimi se -- velmi netradi캜n캩 -- nach치z칤 i modul pro jazyk Python. A jeliko jsou workshopy "eRka콏sk칠", v sekci n칤쬰 je [n치vod](#sec-python-setup), jak celou instalaci zvl치dnout z R konzole RStudia. Kv콢li n치rok콢m na v칳po캜etn칤 v칳kon je ale tento krok sp칤코e doporu캜en칳[^1] a mo쬹치 bude v칳hodn캩j코칤 a p콏칤jemn캩j코칤 vyu쮂셦 [tento Jupyter Notebook](https://colab.research.google.com/drive/1pseOtmte-9AH6DtDAzatRoDU9KQgLYSU?usp=sharing) v r치mci Google Colab. K pou쮂셨치n칤 (zdarma) je zapot콏eb칤 jen Google 칰캜et.

[^1]: Pokud m치te Apple s "nov칳mi" armov칳mi procesory 콏ady M, tak lze pracovat celkem v pohod캩. Jen je t콏eba mal칳 trik, kter칳 si uk치쬰me.

## Interprety[^2] programovac칤ch jazyk콢 a IDE

[^2]: Ano, v 캜e코tin캩 se opravdu [pou쮂셨치](https://cs.wikipedia.org/wiki/Interpret_(software)) tento term칤n 游땐.

1.  [R](https://cloud.r-project.org/) (verze 4.0.0 a nov캩j코칤)

2.  [Python](https://www.python.org/) (ide치ln캩 ve [verzi 3.11.6](https://www.python.org/downloads/release/python-3116/)[^3])

3.  [RStudio Desktop](https://posit.co/download/rstudio-desktop/)[^4] IDE v aktu치ln칤 verzi

[^3]: Ostatn칤 verze by pro na코e pot콏eby tak칠 fungovat *m캩ly*. Tedy krom캩 Pythonu 3.12, pro kter칳 zat칤m nen칤 modul `pythorch`.

[^4]: M콢쬰te i ["cloudov캩"](https://posit.cloud/).

## Bal칤ky do R

-   `tidyverse`
-   `here`
-   `tidytext`
-   `topicmodels`
-   `LDAvis`
-   `ldatuning`
-   `reticulate` (kdy budete cht칤t zkou코et Python v R)

## Moduly do Pythonu

-   `bertopic` (verze 0.15.0)

### Doporu캜en칳 postup instalace p콏es R a RStudio {#sec-python-setup}

```{r}
#| eval: false

library(reticulate)

# nainstalujeme utilitu pro spr치vu izolovan칳ch prost콏ed칤 Pythonu
install_miniconda()

# vytvo콏칤me prost콏ed칤 s n치zvem "topic_modeling", z치kladem bude Python 3.11.6
conda_create("topic_modeling", python_version = "3.11.6")

# nainstalujeme do n캩j modul bertopic 0.15.0
conda_install("topic_modeling", "bertopic==0.15.0")

# vy쮂멳치me specifickou verzi z치vislosti bertopicu, kter치 funguje...
conda_install("topic_modeling", "transformers==4.35.2")

# pou쬴jeme nastaven칠 prost콏ed칤
use_condaenv("topic_modeling")

# potvrd칤me si, 쬰 RStudio pracuje s dan칳m prost콏ed칤m
# n캩kdy je nutn칠 restartovat R session
py_config()
```
